### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [5]:
vector = np.random.uniform(size=10)
vector, vector.shape

(array([0.24090789, 0.34750106, 0.52792432, 0.38251373, 0.43164729,
        0.39504926, 0.09927084, 0.6611718 , 0.46057514, 0.91818015]),
 (10,))

In [13]:
matrix = np.array([[11 + 3 * (3 * i + j) for j in range(3)] for i in range(3)])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [20]:
modified_vector = np.round(vector + 10, 2)
modified_vector

array([10.24, 10.35, 10.53, 10.38, 10.43, 10.4 , 10.1 , 10.66, 10.46,
       10.92])

In [22]:
doubled_matrix = matrix * 2
doubled_matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [24]:
squared_vector = vector ** 2
squared_vector

array([0.05803661, 0.12075698, 0.27870409, 0.14631675, 0.18631938,
       0.15606392, 0.0098547 , 0.43714815, 0.21212946, 0.84305478])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [25]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

1.

In [31]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

2. Результатом множення матриці розміром (2, **2**) на (**2**, 1) буде структура (матриця/вектор) розміром (2, 1)

In [30]:
result_matrix_mult_v = np.dot(result_matrix, C)
result_matrix_mult_v, result_matrix_mult_v.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

3. Результатом множення матриці розміром (2, **2**) на (**2**, 2) буде структура (матриця) розміром (2, 2)

In [32]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [33]:
#1 Транспонуйте result_matrix

result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [34]:
#2 Зробіть транспонування вектора vector і виведіть форму нової структури. Чи бачите ви зміну?

vector.T, vector.T.shape

(array([0.24090789, 0.34750106, 0.52792432, 0.38251373, 0.43164729,
        0.39504926, 0.09927084, 0.6611718 , 0.46057514, 0.91818015]),
 (10,))

Для вектора vector операція .T не змінює його структуру, оскільки він має розмірність (10,) тобто є одновимірним

In [35]:
#3 Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1.

column_vector = np.expand_dims(vector, axis=1)
column_vector, column_vector.shape

(array([[0.24090789],
        [0.34750106],
        [0.52792432],
        [0.38251373],
        [0.43164729],
        [0.39504926],
        [0.09927084],
        [0.6611718 ],
        [0.46057514],
        [0.91818015]]),
 (10, 1))

Операцію numpy.expand_dims додала розмірності верктору-рядку, перетворивши на вектор-стовпець

In [37]:
#4 Зробіть транспонування column_vector, виведіть результат на екран разом з розмірностями отриманої структури.

column_vector.T, column_vector.T.shape

(array([[0.24090789, 0.34750106, 0.52792432, 0.38251373, 0.43164729,
         0.39504926, 0.09927084, 0.6611718 , 0.46057514, 0.91818015]]),
 (1, 10))

Після транспонування отримуємо вектор-рядок з розміром (1, 10)